[package]
name = "rust-mandel"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = "1.18.0"
eframe = { version = "0.28.1", features = [
    "wgpu",
    "default_fonts",
    "wayland",
    "x11",
], default-features = false }
numtraits = "0.0.1"
rand = "0.8.5"
